Implement multiple-tagging

diff --git a/bin/build-image b/bin/build-image
--- a/bin/build-image
+++ b/bin/build-image
@@ -99,15 +99,46 @@ if [ ! -f Dockerfile ]; then
 fi
 
 #
+# Generate tag
+#
+
+if [ -n "$IMAGE_TAGS" ]; then
+    IFS=' ' read -ra TAGS <<< "$IMAGE_TAGS"
+else
+    IFS=$'\n' TAGS=($(run_hook tag))
+fi
+if [ ${#TAGS[@]} -eq 0 ]; then
+    TAGS=('latest')
+fi
+FIRST_TAG="${TAGS[0]}"
+IFS=' '
+
+function join { local d=$1; shift; echo -n "$1"; shift; printf "%s" "${@/#/$d}"; }
+print_msg "=> Tagging image $IMAGE_NAME with $(join ', ' ${TAGS[@]})"
+
+IMAGE_UNTAGGED="$IMAGE_NAME"
+if [ -n "$FIRST_TAG" ]; then
+	IMAGE_NAME="$IMAGE_NAME:$FIRST_TAG"
+fi
+
+#
 # (1/3) Build step
 #
+
 print_msg "=> Building repository"
 START_DATE=$(date +"%s")
 run_hook pre_build
 if [ -f "hooks/build" ]; then
 	run_hook build
 else
-	docker build --rm --force-rm -t this .
+	TAG_ARGS=()
+	if [ -n "$TAGS" ]; then
+		for tag in "${TAGS[@]}"; do
+			TAG_ARGS+="-t "
+			TAG_ARGS+="$IMAGE_UNTAGGED:$tag "
+		done
+	fi
+	docker build --rm --force-rm -t this ${TAG_ARGS[@]} .
 fi
 run_hook post_build
 END_DATE=$(date +"%s")
@@ -163,37 +194,44 @@ TEST=${TEST:-"Tests passed in $(($DATE_DIFF / 60)) minutes and $(($DATE_DIFF % 6
 #
 START_DATE=$(date +"%s")
 if [ ! -z "$IMAGE_NAME" ]; then
+	CLEANUP=no
 	if [ ! -z "$USERNAME" ] || [ -f $HOME/.dockercfg ] || [ -f $HOME/.docker/config.json ]; then
+		CLEANUP=yes
 		print_msg "=> Pushing image $IMAGE_NAME"
 		run_hook pre_push
 		if [ -f "hooks/push" ]; then
 			run_hook push
 		else
-			docker tag -f this $IMAGE_NAME
 			RETRIES=${RETRIES:-5}
-			for (( i=0 ; ; i++ )); do
-				if [ ${i} -eq ${RETRIES} ]; then
-					echo "Too many retries: failed to push the image ${IMAGE_NAME}"
-					exit 1
-				fi
-				docker push $IMAGE_NAME && break
-				sleep 1
+			for TAG in "${TAGS[@]}"; do
+				print_msg "   Pushing tag $IMAGE_UNTAGGED:$TAG"
+				for (( i=0 ; ; i++ )); do
+					if [ ${i} -eq ${RETRIES} ]; then
+						echo "Too many retries: failed to push the image $IMAGE_UNTAGGED:$TAG"
+						exit 1
+					fi
+					docker push "$IMAGE_UNTAGGED:$TAG" && break
+					sleep 1
+				done
 			done
-			# docker push $IMAGE_NAME 2>&1 | tee /tmp/push-result || true
-			# while cat /tmp/push-result | grep -q "is already in progress"; do
-			#  	 docker push $IMAGE_NAME 2>&1 | tee /tmp/push-result || true
-			# 	 sleep 1
-			# done
 			run_hook post_push
 			print_msg "   Pushed image $IMAGE_NAME"
-			if [ "$EXTERNAL_DOCKER" == "no" ] && [ "$MOUNTED_DOCKER_FOLDER" == "no" ]; then
-				print_msg "   Cleaning up images"
-				docker rmi -f $(docker images -q --no-trunc -a) > /dev/null 2>&1 || true
-			fi
 		fi
 	fi
+	if [ -d /images ] && [ -n $SAVE ]; then
+		CLEANUP=yes
+		IMAGE_PATH="/images/$IMAGE_NAME.tar"
+		print_msg "=> Saving image to $IMAGE_PATH"
+		mkdir -p $(dirname "$IMAGE_PATH")
+		docker save this -o "$IMAGE_PATH"
+	fi
+
+	if [ "$CLEANUP" != "no" ] && [ "$EXTERNAL_DOCKER" == "no" ] && [ "$MOUNTED_DOCKER_FOLDER" == "no" ]; then
+		print_msg "   Cleaning up images"
+		docker rmi -f $(docker images -q --no-trunc -a) > /dev/null 2>&1 || true
+	fi
 else
-	PUSH="Skipping push"
+	PUSH="Skipping push/save"
 	print_msg "   $PUSH"
 fi
 END_DATE=$(date +"%s")
